import shinramyunImg from "../../assets/shinramyeon.jpg";
import cocacolaImg from "../../assets/cocacola.jpg";
import jjajangImg from "../../assets/jjajang.jpg";
import potetochipImg from "../../assets/potetochip.webp";
import seawookkangImg from "../../assets/seowookkang.webp";
import sosiziImg from "../../assets/sosizi.jpg";

export const aiLowestCategories = [
  { id: "all", name: "전체" },
  { id: "ramen", name: "라면" },
  { id: "snack", name: "과자" },
  { id: "drink", name: "음료" },
  { id: "instant", name: "즉석식품" },
  { id: "processed", name: "가공식품" },
];

export const aiLowestProducts = [
  {
    id: 1,
    categoryId: "ramen",
    name: "농심 신라면 120g, 5개",
    brand: "농심",
    image: shinramyunImg,
    currentPrice: 4150,
    lowestPrice: 3980,
    dropAmount: 850,
    dropRate: 17,
    aiRecommendation: "지금 구매 추천",
    aiDescription:
      "최근 7일 평균 대비 가격이 충분히 낮아 구매 타이밍이 좋아요.",
    trendPoints: [4420, 4360, 4300, 4210, 4150],
    trendLabels: ["3월", "4월", "현재"],
    badgeType: "primary",
  },
  {
    id: 2,
    categoryId: "drink",
    name: "코카콜라 캔 190ml, 30개",
    brand: "코카콜라",
    image: cocacolaImg,
    currentPrice: 16630,
    lowestPrice: 15980,
    dropAmount: 17060,
    dropRate: 50,
    aiRecommendation: "최저가 근접",
    aiDescription: "단기 하락폭이 커서 지금 구매해도 손해 가능성이 낮아요.",
    trendPoints: [22300, 21400, 20100, 18200, 16630],
    trendLabels: ["3월", "4월", "현재"],
    badgeType: "accent",
  },
  {
    id: 3,
    categoryId: "instant",
    name: "오뚜기 3분 쇠고기 짜장 200g, 1개",
    brand: "오뚜기",
    image: jjajangImg,
    currentPrice: 980,
    lowestPrice: 930,
    dropAmount: 160,
    dropRate: 14,
    aiRecommendation: "조금 더 기다리기",
    aiDescription:
      "최근 하락세는 있지만 추가 하락 가능성이 조금 더 남아 있어요.",
    trendPoints: [1180, 1140, 1080, 1020, 980],
    trendLabels: ["3월", "4월", "현재"],
    badgeType: "default",
  },
  {
    id: 4,
    categoryId: "snack",
    name: "농심 포테토칩 오리지널 60g, 1개",
    brand: "농심",
    image: potetochipImg,
    currentPrice: 5480,
    lowestPrice: 5210,
    dropAmount: 420,
    dropRate: 7,
    aiRecommendation: "가격 하락중",
    aiDescription: "추세상 하락 구간에 있어 조금 더 관찰해도 괜찮아요.",
    trendPoints: [5890, 5780, 5660, 5590, 5480],
    trendLabels: ["3월", "4월", "현재"],
    badgeType: "accent",
  },
  {
    id: 5,
    categoryId: "snack",
    name: "농심 새우깡 오리지널 90g, 1개",
    brand: "농심",
    image: seawookkangImg,
    currentPrice: 900,
    lowestPrice: 870,
    dropAmount: 150,
    dropRate: 14,
    aiRecommendation: "지금 구매 추천",
    aiDescription: "현재 가격이 최근 최저가에 매우 가까워 구매 효율이 좋아요.",
    trendPoints: [1040, 990, 960, 930, 900],
    trendLabels: ["3월", "4월", "현재"],
    badgeType: "primary",
  },
  {
    id: 6,
    categoryId: "processed",
    name: "롯데 맛있는 비엔나 소시지 1kg, 1개",
    brand: "롯데",
    image: sosiziImg,
    currentPrice: 5860,
    lowestPrice: 5520,
    dropAmount: 1390,
    dropRate: 19,
    aiRecommendation: "최저가 근접",
    aiDescription:
      "최근 하락 폭이 커서 지금 구매해도 만족도가 높을 가능성이 커요.",
    trendPoints: [7200, 6810, 6490, 6180, 5860],
    trendLabels: ["3월", "4월", "현재"],
    badgeType: "accent",
  },
];
