import shinramyunImg from "../../assets/shinramyeon.jpg";
import cocacolaImg from "../../assets/cocacola.jpg";
import jjajangImg from "../../assets/jjajang.jpg";
import potetochipImg from "../../assets/potetochip.webp";
import seawookkangImg from "../../assets/seowookkang.webp";
import sosiziImg from "../../assets/sosizi.jpg";

export const productCategories = [
  { id: "all", name: "전체" },
  { id: "ramen", name: "라면" },
  { id: "snack", name: "과자" },
  { id: "drink", name: "음료" },
  { id: "instant", name: "즉석식품" },
  { id: "processed", name: "가공식품" },
];

export const allProducts = [
  {
    id: 1,
    categoryId: "ramen",
    name: "농심 신라면 120g, 5개",
    brand: "농심",
    price: 4150,
    originalPrice: 5000,
    rating: 4.5,
    reviewCount: 128,
    image: shinramyunImg,
    aiTag: "AI 추천",
    badgeType: "primary",
  },
  {
    id: 2,
    categoryId: "drink",
    name: "코카콜라 캔 190ml, 30개",
    brand: "코카콜라",
    price: 16630,
    originalPrice: 33690,
    rating: 3.5,
    reviewCount: 83,
    image: cocacolaImg,
    aiTag: "가격 하락중",
    badgeType: "accent",
  },
  {
    id: 3,
    categoryId: "instant",
    name: "오뚜기 3분 쇠고기 짜장 200g, 1개",
    brand: "오뚜기",
    price: 980,
    originalPrice: 840,
    rating: 4.5,
    reviewCount: 57,
    image: jjajangImg,
    aiTag: "인기 상품",
    badgeType: "default",
  },
  {
    id: 4,
    categoryId: "snack",
    name: "농심 포테토칩 오리지널 60g, 1개",
    brand: "농심",
    price: 5480,
    originalPrice: 5680,
    rating: 4.5,
    reviewCount: 96,
    image: potetochipImg,
    aiTag: "AI 추천",
    badgeType: "primary",
  },
  {
    id: 5,
    categoryId: "snack",
    name: "농심 새우깡 오리지널 90g, 1개",
    brand: "농심",
    price: 900,
    originalPrice: 1050,
    rating: 5.0,
    reviewCount: 211,
    image: seawookkangImg,
    aiTag: "최저가",
    badgeType: "accent",
  },
  {
    id: 6,
    categoryId: "processed",
    name: "롯데 맛있는 비엔나 소시지 1kg, 1개",
    brand: "롯데",
    price: 5860,
    originalPrice: 7250,
    rating: 4.0,
    reviewCount: 73,
    image: sosiziImg,
    aiTag: "가격 하락중",
    badgeType: "accent",
  },
  {
    id: 7,
    categoryId: "ramen",
    name: "농심 안성탕면 125g, 5개",
    brand: "농심",
    price: 3890,
    originalPrice: 4500,
    rating: 4.3,
    reviewCount: 64,
    image: shinramyunImg,
    aiTag: "AI 추천",
    badgeType: "primary",
  },
  {
    id: 8,
    categoryId: "drink",
    name: "코카콜라 제로 355ml, 24개",
    brand: "코카콜라",
    price: 18900,
    originalPrice: 22900,
    rating: 4.6,
    reviewCount: 141,
    image: cocacolaImg,
    aiTag: "인기 상품",
    badgeType: "default",
  },
  {
    id: 9,
    categoryId: "instant",
    name: "오뚜기 3분 카레 순한맛 200g, 1개",
    brand: "오뚜기",
    price: 1100,
    originalPrice: 1400,
    rating: 4.2,
    reviewCount: 39,
    image: jjajangImg,
    aiTag: "최저가",
    badgeType: "accent",
  },
];
